[tool.poetry]
name = "aime2026"
version = "0.1.0"
description = ""
authors = ["patriziobellan86 <patrizio.bellan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
